"use client";

import React from "react";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { motion } from "framer-motion";
import { toast } from "sonner";
import { api } from "../../lib/api";
import { MedicalBanner } from "../../components/MedicalBanner";
import { Disclaimer } from "../../components/Disclaimer";
import type { UserProfile } from "../../lib/types";

export default function PlannerPage() {
  const qc = useQueryClient();
  const { data: profile } = useQuery({ queryKey: ["profile"], queryFn: api.getProfile });
  const { data: plan } = useQuery({ queryKey: ["plan"], queryFn: api.getPlan });

  const [confirmed, setConfirmed] = React.useState(false);

  const genMut = useMutation({
    mutationFn: () => api.generatePlan(!!confirmed),
    onSuccess: (res) => {
      if (res.needs_confirmation) {
        toast.error("Please check the confirmation box first (medical flags detected).");
        return;
      }
      toast.success("Weekly plan generated");
      if (res.used_fallback) toast.warning("Fallback planner used — great results still, but set an LLM key for richer plans.");
      qc.invalidateQueries({ queryKey: ["plan"] });
      qc.invalidateQueries({ queryKey: ["recipes"] });
    },
    onError: (e: any) => {
      const d = e?.message || "";
      if (d.includes("confirmation")) {
        toast("Medical confirmation required for this profile.");
      } else {
        toast.error(d || "Plan generation failed");
      }
    },
  });

  const needsConfirm = profile && (
    profile.health_flags?.has_medical_condition ||
    profile.health_flags?.is_pregnant_or_breastfeeding ||
    profile.health_flags?.cooking_for_children ||
    profile.health_flags?.cooking_for_elderly
  );

  return (
    <div className="max-w-4xl space-y-6">
      <div className="flex items-center gap-4">
        <div className="flex-1">
          <h1 className="section-header">Weekly meal planner</h1>
          <p className="text-[#4a635c]">7-day balanced plan with leftover awareness, generated by the full agent pipeline.</p>
        </div>
        <img src="/images/samosas.jpg" alt="Crispy samosas inspiration" className="w-28 h-20 object-cover rounded-2xl border border-[var(--np-border)] hidden sm:block" />
      </div>

      <MedicalBanner profile={profile} />

      {needsConfirm && (
        <label className="flex items-start gap-3 text-sm bg-white p-4 rounded-xl border border-[#e2ebe6]">
          <input type="checkbox" checked={confirmed} onChange={(e) => setConfirmed(e.target.checked)} className="mt-0.5" />
          <span>I understand this is general meal inspiration only, not medical advice.</span>
        </label>
      )}

      <button
        onClick={() => genMut.mutate()}
        disabled={genMut.isPending || (needsConfirm && !confirmed)}
        className="btn btn-primary min-w-[240px]"
      >
        {genMut.isPending ? "Running full agent pipeline..." : "Generate weekly plan"}
      </button>

      {genMut.isPending && (
        <div className="card bg-white">
          <div className="text-sm font-medium mb-2 text-[#1a3c34]">Full agent flow in progress</div>
          <div className="space-y-1 text-sm">
            <div className="agent-step done">✓ InventoryAgent — prioritizing pantry + KB insights</div>
            <div className="agent-step done">✓ RecipeCreator — generating candidate recipes</div>
            <div className="agent-step active">⟳ MealPlanner — building 7-day schedule with leftovers &amp; variety</div>
            <div className="agent-step">… ShoppingListOptimizer ready after plan</div>
          </div>
          <div className="text-[10px] text-[#4a635c] mt-2">This is where the agentic magic happens. Please wait (can be 30–90s first time).</div>
        </div>
      )}

      {!plan && <div className="text-sm text-[#4a635c]">No plan yet. Generate one above.</div>}

      {plan && (
        <div className="space-y-6">
          {plan.compromises && <div className="text-sm italic text-[#4a635c]">Compromises: {plan.compromises}</div>}
          {plan.leftover_strategy && <div className="text-sm italic text-[#4a635c]">Leftovers strategy: {plan.leftover_strategy}</div>}

          {plan.days?.map((day: any, idx: number) => (
            <motion.div 
              key={idx} 
              className="card"
              initial={{ opacity: 0, y: 10 }}
              animate={{ opacity: 1, y: 0 }}
              transition={{ delay: idx * 0.04 }}
            >
              <div className="font-semibold mb-3">{day.day_label}</div>
              <div className="space-y-1.5 text-sm">
                {day.meals.map((m: any, i: number) => (
                  <div key={i} className="flex gap-2">
                    <span className="w-20 text-[#4a635c] capitalize">{m.slot}</span>
                    <span>{m.recipe_name}</span>
                    {m.uses_leftovers_from && <span className="text-xs self-center text-[#4a635c]">(leftovers from {m.uses_leftovers_from})</span>}
                    {m.notes && <span className="text-xs self-center text-[#4a635c] ml-2">— {m.notes}</span>}
                  </div>
                ))}
              </div>
            </motion.div>
          ))}

          <Disclaimer text={plan.disclaimer} />
        </div>
      )}
    </div>
  );
}
